modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
license = "MIT"

[[mods]]
modId = "hexkinetics"
version = "${version}"
displayName = "HexKinetics"
logoFile = "icon.png"
authors = "Sonunte"
description = '''
An addon mod for Hex Casting that adds additional operations on vectors and some spells/
'''

[[dependencies.hexkinetics]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexkinetics]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexkinetics]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexkinetics]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingVersion},)"
ordering = "NONE"
side = "BOTH"
